#### 다중 회귀

- 여러 개의 특성을 사용한 선형 회귀

- 특성 공학 : 기존의 특성을 사용해 새로운 특성을 뽑아내는 작업

#### 데이터 준비
- 판다스 : 데이터 분석 라이브러리
- 데이터프레임 : 판다스의 핵심 데이터 구조

In [48]:
import pandas as pd
#df = pd.read_csv('http://bit.ly/perch_csv_data')
df = pd.read_csv('../datas/perch_full.csv')
perch_full = df.to_numpy()
print(perch_full)

[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]
 [16.2   4.59  2.63]
 [17.4   4.59  2.94]
 [18.    5.22  3.32]
 [18.7   5.2   3.12]
 [19.    5.64  3.05]
 [19.6   5.14  3.04]
 [20.    5.08  2.77]
 [21.    5.69  3.56]
 [21.    5.92  3.31]
 [21.    5.69  3.67]
 [21.3   6.38  3.53]
 [22.    6.11  3.41]
 [22.    5.64  3.52]
 [22.    6.11  3.52]
 [22.    5.88  3.52]
 [22.    5.52  4.  ]
 [22.5   5.86  3.62]
 [22.5   6.79  3.62]
 [22.7   5.95  3.63]
 [23.    5.22  3.63]
 [23.5   6.28  3.72]
 [24.    7.29  3.72]
 [24.    6.38  3.82]
 [24.6   6.73  4.17]
 [25.    6.44  3.68]
 [25.6   6.56  4.24]
 [26.5   7.17  4.14]
 [27.3   8.32  5.14]
 [27.5   7.17  4.34]
 [27.5   7.05  4.34]
 [27.5   7.28  4.57]
 [28.    7.82  4.2 ]
 [28.7   7.59  4.64]
 [30.    7.62  4.77]
 [32.8  10.03  6.02]
 [34.5  10.26  6.39]
 [35.   11.49  7.8 ]
 [36.5  10.88  6.86]
 [36.   10.61  6.74]
 [37.   10.84  6.26]
 [37.   10.57  6.37]
 [39.   11.14  7.49]
 [39.   11.14  6.  ]
 [39.   12.43  7.35]
 [40.   11.93

In [49]:
import numpy as np

perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [50]:
# 훈련 데이터와 테스트 데이터로 나누기

from sklearn.model_selection import train_test_split

train_input,test_input,train_target,test_target = train_test_split(perch_full,perch_weight,random_state=42)

#### 사이킷런의 변환기

- 특성을 만들거나 전처리 하기 위해 사이킷런에서 제공하는 다양한 클래스
- 모두 fit과 transform() 메서드를 제공

In [51]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)
poly.fit([[2,3]])
poly.transform([[2,3]])

array([[2., 3., 4., 6., 9.]])

In [52]:
poly = PolynomialFeatures(include_bias=False)
poly.fit(train_input)
train_poly = poly.transform(train_input)

test_poly = poly.transform(test_input)

print(train_poly)

print(poly.get_feature_names_out())

[[  19.6       5.14      3.04    384.16    100.744    59.584    26.4196
    15.6256    9.2416]
 [  22.        5.88      3.52    484.      129.36     77.44     34.5744
    20.6976   12.3904]
 [  18.7       5.2       3.12    349.69     97.24     58.344    27.04
    16.224     9.7344]
 [  17.4       4.59      2.94    302.76     79.866    51.156    21.0681
    13.4946    8.6436]
 [  36.       10.61      6.74   1296.      381.96    242.64    112.5721
    71.5114   45.4276]
 [  25.        6.44      3.68    625.      161.       92.       41.4736
    23.6992   13.5424]
 [  40.       11.93      7.11   1600.      477.2     284.4     142.3249
    84.8223   50.5521]
 [  39.       12.43      7.35   1521.      484.77    286.65    154.5049
    91.3605   54.0225]
 [  43.       11.93      7.28   1849.      512.99    313.04    142.3249
    86.8504   52.9984]
 [  22.        5.64      3.52    484.      124.08     77.44     31.8096
    19.8528   12.3904]
 [  20.        5.08      2.77    400.      101.6    

#### 다중 회귀 모델 훈련하기


In [53]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(train_poly,train_target)

print(lr.score(train_poly,train_target))

print(lr.score(test_poly,test_target))

# 이로서 과소적합 문제는 해결했다.
# 특성이 늘어나면 선형 회귀의 능력은 매우 강하다

0.9903183436982126
0.9714559911594143


#### 특성을 더 많이 추가하면?

In [58]:
poly = PolynomialFeatures(degree=5, include_bias=False)
poly.fit(train_input)
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)
train_poly.shape



# 55(배열의 열의 개수가 특성의 개수)

(42, 55)

In [60]:
lr.fit(train_poly,train_target)
print("훈련 세트 {}".format(lr.score(train_poly,train_target)))
print("테스트 세트 {}".format(lr.score(test_poly,test_target)))

훈련 세트 0.999999999998714
테스트 세트 -144.4066764700865


- 특성이 개수를 늘리면 선형 모데를 아주 강력해지나, 과대적합되므로 테스트 세트에서는 형편없는 점수를 만든다

#### 규제
- 머신러닝 모델이 훈련 세트를 너무 과도하게 학습하지 못하도록 훼방하는 것
- 선형 회귀 모델의 경우 특성에 곱해지는 개수의 크기를 작게 만드는 일